apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  completions: 3
  parallelism: 3 # default one by one
  template:
    metadata:
      name: math-addition
      labels:
        app: math-addition
    spec:
      containers:
        - name: math-addition
          image: ubuntu
          command: ["expr", "3", "+", "2"]
      restartPolicy: Never
