apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: demo-cron-job
spec:
  schedule: "*/1 * * * *" # every minute
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3 # default one by one
      template:
        spec:
          containers:
            - name: math-addition
              image: ubuntu
              command: ["expr", "3", "+", "2"]
          restartPolicy: Never
